# GPT Constants
GPT_MODEL = "gpt-3.5-turbo-0613"
MAX_TOKENS = 3000
# Set the temperature to control randomness (lower values make the output more deterministic)
TEMPERATURE = 0.7

pantry_and_spice_ingredients = [
    "flour",
    "sugar",
    "salt",
    "pepper",
    "olive oil",
    "vegetable oil",
    "rice",
    "pasta",
    "canned tomatoes",
    "canned beans",
    "soy sauce",
    "vinegar",
    "mustard",
    "ketchup",
    "mayonnaise",
    "honey",
    "butter",
    "oats",
    "cereal",
    "spices (e.g., oregano, basil, thyme)",
    "herbs (e.g., parsley, cilantro)",
    "garlic powder",
    "onion powder",
    "cinnamon",
    "cumin",
    "paprika",
    "chili powder",
    "red pepper flakes",
    "bay leaves",
    "vanilla extract",
    "baking powder",
    "baking soda",
    "cocoa powder",
    "chocolate chips",
    "nuts",
    "dried fruits",
    "tea bags",
    "coffee",
    "canned tuna",
    "canned soup",
    "crackers",
    "jam",
    "peanut butter",
    "hummus",
    "hot sauce",
    "maple syrup",
    "olives",
    "salsa",
    "tortillas",
    "breadcrumbs",
]
