fridge_ingredients = [
    "Eggs",
    "Milk",
    "Butter",
    "Cheese (cheddar, mozzarella, etc.)",
    "Yogurt",
    "Fresh vegetables (lettuce, tomatoes, carrots, bell peppers, cucumbers)",
    "Fresh fruits (apples, oranges, grapes, berries)",
    "Condiments (ketchup, mustard, mayonnaise)",
    "Pickles",
    "Hummus",
    "Jam or jelly",
    "Bacon",
    "Deli meats (ham, turkey, chicken)",
    "Tofu or tempeh",
    "Salad dressings",
    "Fresh herbs (parsley, cilantro)",
    "Leftover cooked chicken or beef",
    "Various sauces (soy sauce, barbecue sauce)",
    "Lemon or lime",
    "Tortillas or wraps"
]


pantry_and_spice_ingredients = [
    "flour",
    "sugar",
    "salt",
    "pepper",
    "olive oil",
    "vegetable oil",
    "rice",
    "pasta",
    "canned tomatoes",
    "canned beans",
    "soy sauce",
    "vinegar",
    "mustard",
    "ketchup",
    "mayonnaise",
    "honey",
    "butter",
    "oats",
    "cereal",
    "spices (e.g., oregano, basil, thyme)",
    "herbs (e.g., parsley, cilantro)",
    "garlic powder",
    "onion powder",
    "cinnamon",
    "cumin",
    "paprika",
    "chili powder",
    "red pepper flakes",
    "bay leaves",
    "vanilla extract",
    "baking powder",
    "baking soda",
    "cocoa powder",
    "chocolate chips",
    "nuts",
    "dried fruits",
    "tea bags",
    "coffee",
    "canned tuna",
    "canned soup",
    "crackers",
    "jam",
    "peanut butter",
    "hummus",
    "hot sauce",
    "maple syrup",
    "olives",
    "salsa",
    "tortillas",
    "breadcrumbs",
]
GPT_MODEL = "gpt-3.5-turbo-0613"
# Set the maximum number of tokens for the response
MAX_TOKENS = 3000
# Set the temperature to control randomness (lower values make the output more deterministic)
TEMPERATURE = 0.7